# Generated by Django 4.0.5 on 2022-11-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='data/photos/email_data', verbose_name='Лого компании')),
                ('cart_image', models.ImageField(blank=True, null=True, upload_to='data/photos/email_data', verbose_name='Картинка "Корзины"')),
                ('check_image', models.ImageField(blank=True, null=True, upload_to='data/photos/email_data', verbose_name='Картинка "Галочки"')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Данные для Email уведомлений о заказах',
                'verbose_name_plural': 'Данные для Email уведомлений о заказах',
                'db_table': 'emails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='data/photos/features', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Достоинство',
                'verbose_name_plural': 'Достоинства',
                'db_table': 'features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('google_metric', models.CharField(blank=True, max_length=500, null=True, verbose_name='Google метрика')),
                ('yandex_metric', models.CharField(blank=True, max_length=500, null=True, verbose_name='Yandex метрика')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрика',
                'db_table': 'metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('image', models.ImageField(null=True, upload_to='data/photos/services', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('main_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Главный текст')),
                ('upper_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст выше')),
                ('down_text', models.TextField(blank=True, null=True, verbose_name='Текст ниже')),
                ('image', models.ImageField(null=True, upload_to='data/photos/sliders', verbose_name='Фотография')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
                'db_table': 'sliders',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
