# Generated by Django 4.0.5 on 2022-11-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.BigIntegerField(blank=True, null=True, verbose_name='Кол-во')),
                ('total_price', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True, verbose_name='Общая сумма')),
            ],
            options={
                'verbose_name': 'Продукт корзины',
                'verbose_name_plural': 'Продукты корзин',
                'db_table': 'cart_products',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('in_order', models.BooleanField(blank=True, editable=False, null=True, verbose_name='В заказе')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'carts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='data/catalogs')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
                'db_table': 'catalogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='data/photos/categories', verbose_name='Фото категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Корзина избранных',
                'verbose_name_plural': 'Корзины избранных',
                'db_table': 'favourites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavouritesProducts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Избранный продукт',
                'verbose_name_plural': 'Избранные продукты',
                'db_table': 'favourites_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OptionOfDeliveryAndPayments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('city', models.TextField(blank=True, null=True, verbose_name='Город')),
                ('street', models.TextField(blank=True, null=True, verbose_name='Улица')),
                ('house', models.TextField(blank=True, null=True, verbose_name='Дом')),
                ('frame', models.TextField(blank=True, null=True, verbose_name='Корпус')),
                ('entrance', models.TextField(blank=True, null=True, verbose_name='Подъезд')),
                ('apartment_office', models.TextField(blank=True, null=True, verbose_name='Квартира/Оффис')),
            ],
            options={
                'verbose_name': 'Информация о доставке',
                'verbose_name_plural': 'Информация о доставке',
                'db_table': 'option_of_delivery_and_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatuses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
                'db_table': 'order_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('vendor_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('code1c', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код 1с')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена')),
                ('image_original', models.ImageField(blank=True, null=True, upload_to='data/photos/products/products_original', verbose_name='Главная фотография')),
                ('image_128', models.ImageField(blank=True, null=True, upload_to='data/photos/products/products_128', verbose_name='Фотография 128px')),
                ('image_432', models.ImageField(blank=True, null=True, upload_to='data/photos/products/products_432', verbose_name='Фотография 432px')),
                ('can_to_view', models.BooleanField(help_text='На сайте отоброжаются только те продукты, где данное поле принимает значение "Да" | По умолчанию при добавлении продукта данное поле имеет положительно значение', verbose_name='Разрешение на публикацию')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('inn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Форма покупателя',
                'verbose_name_plural': 'Формы покупателей',
                'db_table': 'users',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
