# Generated by Django 4.0.5 on 2022-11-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание к заказу')),
                ('order_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.orderstatuses', verbose_name='Статус заказа')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.users', verbose_name='Покупатель')),
            ],
        ),
    ]
