# Generated by Django 4.0.5 on 2022-11-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
